apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: ladesa-ro-development

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: ladesa-ro-api-configmap
    env: config.properties
